### ISSUE TITLE
bug in README.md

### ISSUE THREAD

**Issue by cyeh1234** [AnnaPS/infogames#3]
GAMES_API_KEY = 'your api key code here';  should be in your .env file not YOUR_API_KEY

For this project I used .env directory to store my API Key, if you want to use it, you need to create this structure on the root of your app:

````
assets:
  - .env
````

Inside this file you need to put your API KEY like that:

````
**YOUR_API_KEY** = 'your api key code here';



<img width="1401" alt="image" src="https://user-images.githubusercontent.com/5484253/159194378-f0ffc39c-9d3d-42d6-ad6a-fad6c98ccc70.png">

**Comment by AnnaPS** [comment]
Yes, you're right. Perhaps is more understandable if I called "**GAMES_API_KEY**". Thanks for the feedback.
Next time if you want, you could open a PR with the change and I'll check it 😀

**Comment by cyeh1234** [comment]
Anna,

Here's a Github repository with fix
https://github.com/cyeh1234/infogames-master-main-main-2fix

I modified gitignore so .env can be committed; I don't mind others using my
APIkey.

You're a lot quicker dealing with open issues.

Here is a link to an open issue I created; it's still open

https://github.com/MattHamburger/clean_framework/issues/44

Charles

**Comment by AnnaPS** [comment]
@cyeh1234 the .env file should not be exposed because it's a security breach. The API KEY should be hidden from users, if you want to show your API KEY in your projects is up to you, but in my repositories, the secret API KEYs will be hidden.

Thanks!

**Comment by cyeh1234** [comment]
ok; no problem. just trying to make easier for other to build your app without going through trouble of getting a free apikey.
