### ISSUE TITLE
'Const variables must be initialized with a constant value'.

### ISSUE THREAD

**Issue by salkhan-ops** [AnnaPS/infogames#6]
![Picture1](https://user-images.githubusercontent.com/65277891/170669727-be0e6652-a9df-44bf-8de3-640f0fdbaf2d.png)
Thank you for the nice tutorial. Very informative.

There is an error, i can't figure out i.e., repositories/game.dart, line filters: Filters(years: [ ]), causing 'Const variables must be initialized with a constant value'.t

**Comment by AnnaPS** [comment]
Thanks for your feedback!
If you have time, you could open a new PR with the change and I'll check and merge it. 
If you don't have enough time, don't worry, I'll tackle this in the next few weeks.
Thanks!

**Comment by salkhan-ops** [comment]
Dont worry. The list 'empty' shouldnt be constant. Removing const before the 'empty' fixed the error. Thank for the response.

**Comment by salkhan-ops** [comment]
Issue fixed
